# Generated by Django 4.0.2 on 2022-02-25 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-created', '-updated']},
        ),
    ]
