# Generated by Django 4.0.2 on 2022-02-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpost_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='story',
            field=models.TextField(blank=True, null=True),
        ),
    ]
