# Generated by Django 4.0.2 on 2022-02-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpost_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='blogTitle',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
