# Generated by Django 4.0.2 on 2022-02-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogpost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
